### PR TITLE
Adds bypass to SSL verification through option in config

### PR DESCRIPTION
**Pull request by acambitsis**
Helps with [this](https://github.com/craigbarratt/hass-pyscript-jupyter/issues/16) issue.

Sorry for the formatting changes - they weren't intentional.  Hope that's ok.

### CODE REVIEW

**Comment by craigbarratt** [comment]
Thanks for submitting.  While I prefer the more compact formatting, I decided to standardize on the same formatting that HASS uses.  For pyscript I set these up to automatically run when you push, but for this repository it's still manual.

Here are the formatting / checking commands I run:
```
isort hass_pyscript_kernel/*py
black hass_pyscript_kernel
flake8 hass_pyscript_kernel/*py
pylint hass_pyscript_kernel/*py
```
Can you run these and confirm the formatting is now unchanged?  If so, please update the PR.

**Comment by acambitsis** [comment]
Sure.  Thanks for that guidance.  If I don't get to it today will do it
tomorrow morning.

All the best,
Andreas.

**Comment by acambitsis** [comment]
@craigbarratt commit with format changes done.  Let me know if all good.

**Comment by craigbarratt** [comment]
Looks good - thanks for submitting the PR.

**Pull request merged**
